FROM golang:1.16-alpine AS builder

# move to working directory
WORKDIR /build

# copy and download dependencies using go.mod and go.sum
COPY go.mod go.sum ./
RUN go mod download

# Copy the code into the container
COPY ./sender/main.go .

# set necessary env variables for the image and for building
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -ldflags="-s -w" -o sender .

FROM scratch
# Copy binary and config files from /build
# to root folder of scratch container.
COPY --from=builder ["/build/sender", "/"]

ENTRYPOINT ["/sender"]
