FROM golang:1.20-alpine AS builder

# Move to working directory (/build)
WORKDIR /build

# copy go.mod and go.sum to working directory and download dependencies using them
COPY go.mod go.sum ./
RUN go mod download

# copy the code into the conainer
COPY ./consumer/main.go .

# Set necessary environment variables needed
# for our image and build the consumer.

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -ldflags="-s -w" -o consumer .

FROM scratch

# Copy binary and config files from /build
# to root folder of scratch container.
COPY --from=builder ["/build/consumer", "/"]

ENTRYPOINT ["/consumer"]
